Catalog modifications
fortinet/ibm-fortigate-terraform-deploy pull request #2
Opened 2021-04-08 21:02 UTC by Joel-Cripps

Requested changes for the IBM catalog single image.

Changes include:
 - No longer automatically creates vpc/subnet/ etc. All of those will need to be input by the end user and created ahead of time.
 - SSH key is now a data reference
 - TF_VERSION enforced for catalog use.
 - 7.0 is now the image default.

Will need to be tested and validated before release.

2021-04-08 21:06 UTC, jamie-pate approved these changes

2021-04-08 21:49 UTC, JaydenLiang approved these changes
looks good to me.

2021-04-12 17:39 UTC, Joel-Cripps commented
Adjusted a couple of things:
1. Now uses just the standard 7.0 image. Map vars fail to parse in the validation.
2. New README updates using full links. Will now show in IBM if no links present.

2021-04-12 18:38 UTC, jamie-pate requested changes

2021-04-12 18:38 UTC, jamie-pate commented on README.md
> +![IBM FortiGate Deploy](https://raw.githubusercontent.com/fortinet/ibm-fortigate-terraform-deploy/main/imgs/imgs/step_6_a.png)
imgs/imgs ?
https://raw.githubusercontent.com/fortinet/ibm-fortigate-terraform-deploy/main/imgs/step_6_a.png seems correct

2021-04-12 18:38 UTC, jamie-pate commented on README.md
> +![IBM FortiGate Deploy](https://raw.githubusercontent.com/fortinet/ibm-fortigate-terraform-deploy/main/imgs/imgs/step_6_a.png)
also a bunch of cases below

2021-04-12 21:28 UTC, jamie-pate approved these changes

2021-04-12 21:30 UTC, JaydenLiang approved these changes

2021-04-12 21:38 UTC, merged